# Generated by Django 3.1 on 2024-02-26 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20240222_2353'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'store', 'verbose_name_plural': 'products'},
        ),
    ]
