# Generated by Django 3.1 on 2024-02-29 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_variation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variation',
            old_name='variaton_category',
            new_name='variation_category',
        ),
        migrations.RenameField(
            model_name='variation',
            old_name='variaton_value',
            new_name='variation_value',
        ),
    ]
