# Generated by Django 3.1 on 2024-02-26 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='card_id',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
